@extends('layouts.app')
@section('title','Create payment')
@section('content')
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Outfit:wght@400;500;600;700;800&display=swap');
.pc{background:#f4f5fa;min-height:100vh;padding:34px clamp(17px,4vw,60px) 85px;color:#1c2851;font-family:'DM Sans',sans-serif}.pc *{box-sizing:border-box}.pc-wrap{max-width:1160px;margin:auto}.pc-back{font-size:13px;color:#5c52b0;text-decoration:none;font-weight:800}.pc-head{margin:28px 0 32px}.pc-head h1{font:700 clamp(38px,5vw,66px) Outfit;letter-spacing:-.055em;line-height:1.03;margin:0 0 11px}.pc-head p{color:#65708d;line-height:1.6;margin:0;max-width:620px}.pc-layout{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(290px,.75fr);gap:21px}.pc-form,.pc-side{background:white;border:1px solid #e1e5f1;border-radius:19px;padding:clamp(24px,3vw,40px)}.pc-form h2,.pc-side h2{font:700 27px Outfit;letter-spacing:-.04em;margin:0 0 20px}.pc-field{margin-bottom:21px}.pc-field label,.pc-label{display:block;font-size:13px;font-weight:800;margin-bottom:9px}.pc-field input,.pc-field select,.pc-field textarea{display:block;width:100%;padding:13px 15px;border:1px solid #cdd4e6;background:#fafbff;color:#1d2c56;border-radius:10px;font:500 14px 'DM Sans',sans-serif}.pc-field input:focus,.pc-field select:focus,.pc-field textarea:focus{outline:none;border-color:#685cc2;box-shadow:0 0 0 3px #e3dffa}.pc-field small{display:block;color:#74809b;font-size:12px;margin-top:7px}.pc-methods{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.pc-method{position:relative}.pc-method input{position:absolute;opacity:0}.pc-method label{display:block;height:100%;padding:17px;border:1px solid #d9deef;border-radius:12px;cursor:pointer;background:#f9faff;font-weight:800;font-size:14px}.pc-method label small{display:block;color:#6f7896;font-weight:500;margin-top:6px;line-height:1.4}.pc-method input:checked+label{border-color:#6759be;background:#efedfb;box-shadow:inset 0 0 0 1px #6759be}.pc-method input:focus-visible+label{outline:3px solid #a49add}.pc-submit{border:0;background:#5c50b1;color:white;padding:15px 25px;border-radius:10px;font:800 14px 'DM Sans',sans-serif;cursor:pointer;width:100%;margin-top:5px}.pc-submit:disabled{opacity:.5}.pc-side{align-self:start;background:#e9e9f7}.pc-side p{color:#56627d;line-height:1.65;font-size:13px;margin:0 0 17px}.pc-side ol{padding-left:20px;color:#344166;font-size:13px;line-height:1.8}.pc-note{border-top:1px solid #ccd0e9;padding-top:17px;margin-top:20px!important}.pc-error{background:#fde9e8;color:#8c3d39;padding:12px 15px;border-radius:10px;margin:0 0 20px}.pc-card{display:none;margin:18px 0}.pc-card.active{display:block}.pc-empty{background:white;border-radius:16px;padding:30px}.pc-fieldset{border:0;padding:0;margin:0 0 23px}.pc-fieldset legend{font-weight:800;font-size:13px;margin-bottom:9px}
@media(max-width:760px){.pc-layout{grid-template-columns:1fr}.pc-methods{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.pc *{transition:none!important}}
.pc-empty{border:1px solid #e1e5f1;padding:clamp(36px,5vw,70px);max-width:820px}.pc-empty h2{font:700 clamp(26px,3vw,37px) Outfit;letter-spacing:-.04em;margin:0 0 12px}.pc-empty p{color:#65708d;line-height:1.65;max-width:550px;margin:0 0 22px}.pc-empty a{display:inline-block;background:#5c50b1;color:white;text-decoration:none;border-radius:9px;padding:12px 17px;font-weight:800;font-size:13px}
</style>
<main class="pc"><div class="pc-wrap"><a class="pc-back" href="{{ route('payments.index') }}">Back to payments</a><header class="pc-head"><h1>Make a payment.</h1><p>Choose a configured method, confirm the amount, and follow the next steps. Transfers stay pending until Tasmiya verifies receipt.</p></header>
@if($errors->any())<div class="pc-error" role="alert">{{ $errors->first() }}</div>@endif
@if(session('error'))<div class="pc-error" role="alert">{{ session('error') }}</div>@endif
@if(empty($methods))<div class="pc-empty"><h2>No payment methods are available yet.</h2><p>An administrator needs to add a receiving account in Integrations before payments can be created.</p>@if(auth()->user()?->isAdmin())<a href="{{ route('settings.index') }}">Open Integrations</a>@endif</div>
@else
<div class="pc-layout"><form id="paymentForm" class="pc-form" method="POST" action="{{ route('payments.store') }}">@csrf<h2>Payment details</h2>
<div class="pc-field"><label for="service_id">Service</label><select id="service_id" name="service_id"><option value="">Custom payment amount</option>@foreach($services as $service)<option value="{{ $service->id }}" data-price="{{ $service->price }}" @selected(old('service_id')==$service->id)>{{ $service->name }} — PKR {{ number_format($service->price,2) }}</option>@endforeach</select><small>Service prices are set by Tasmiya. Custom payments can use an amount you enter.</small></div>
<div class="pc-field"><label for="amount">Amount in PKR</label><input id="amount" name="amount" type="number" step="0.01" min="0.01" max="999999.99" value="{{ old('amount') }}" required><small>When a service is selected, its saved price is used by the server.</small></div>
<fieldset class="pc-fieldset"><legend>Payment method</legend><div class="pc-methods">@foreach($methods as $key=>$method)<div class="pc-method"><input id="pm-{{ $key }}" type="radio" name="payment_method" value="{{ $key }}" @checked(old('payment_method')===$key || (!old('payment_method') && $loop->first))><label for="pm-{{ $key }}">{{ $method['label'] }}<small>{{ $method['mode']==='manual' ? 'Transfer in your app, then submit a reference.' : 'Secure card checkout.' }}</small></label></div>@endforeach</div></fieldset>
<div class="pc-field"><label for="description">Description (optional)</label><textarea id="description" name="description" rows="3" maxlength="500" placeholder="What is this payment for?">{{ old('description') }}</textarea></div>
@if(isset($methods['card']))<div id="cardArea" class="pc-card"><div class="pc-label">Card details</div><div id="card-element" style="border:1px solid #cdd4e6;border-radius:10px;padding:14px"></div></div>@endif
<div id="paymentError" class="pc-error" role="alert" hidden></div><button id="paymentSubmit" class="pc-submit" type="submit">Continue</button></form>
<aside class="pc-side"><h2>What happens next</h2><ol><li>Create a payment record.</li><li>Transfer the exact amount to the account shown on the next page.</li><li>Submit your transaction reference and optional receipt.</li><li>Wait for an administrator to verify the incoming funds.</li></ol><p class="pc-note">A reference or screenshot is evidence for review, not proof that funds arrived. Your status changes to paid only after verification.</p></aside></div>
@endif</div></main>
@if(isset($methods['card']))
<script src="https://js.stripe.com/v3/"></script><script>
document.addEventListener('DOMContentLoaded',()=>{
 const stripe=window.Stripe(@json($methods['card']['public_key'])); const card=stripe.elements().create('card'); let mounted=false;
 const area=document.getElementById('cardArea'); const form=document.getElementById('paymentForm');
 const change=()=>{const selected=form.querySelector('input[name="payment_method"]:checked')?.value;area.classList.toggle('active',selected==='card');if(selected==='card'&&!mounted){card.mount('#card-element');mounted=true;}};
 form.querySelectorAll('input[name="payment_method"]').forEach(input=>input.addEventListener('change',change));change();
 form.addEventListener('submit',async event=>{if(form.querySelector('input[name="payment_method"]:checked')?.value!=='card')return;event.preventDefault();
 const button=document.getElementById('paymentSubmit');const errorBox=document.getElementById('paymentError');button.disabled=true;errorBox.hidden=true;
 try{const data=new FormData(form);const response=await fetch(form.action,{method:'POST',headers:{'Accept':'application/json','X-CSRF-TOKEN':@json(csrf_token())},body:data});const payload=await response.json();if(!response.ok)throw new Error(payload.message||payload.error||'Card payment could not begin.');const result=await stripe.confirmCardPayment(payload.client_secret,{payment_method:{card}});if(result.error)throw new Error(result.error.message);window.location.href=@json(url('/payments'))+'/'+payload.payment_id;}catch(error){errorBox.textContent=error.message;errorBox.hidden=false;button.disabled=false;}
 });
});
</script>
@endif
<script>document.addEventListener('DOMContentLoaded',()=>{const select=document.getElementById('service_id'),amount=document.getElementById('amount');if(!select)return;const sync=()=>{const price=select.selectedOptions[0]?.dataset.price;if(price){amount.value=price;amount.readOnly=true}else amount.readOnly=false};select.addEventListener('change',sync);sync();});</script>
@endsection
