@extends('layouts.app')
@section('title','Payments')
@section('content')
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Outfit:wght@400;500;600;700;800&display=swap');
.pl{background:#f4f5fa;min-height:100vh;padding:33px clamp(16px,4vw,64px) 90px;color:#1b2751;font-family:'DM Sans',sans-serif}.pl *{box-sizing:border-box}.pl-inner{max-width:1280px;margin:auto}.pl-top{display:flex;justify-content:space-between;align-items:end;gap:20px;margin:25px 0 26px}.pl-top h1{font:700 clamp(38px,4.8vw,64px) Outfit;letter-spacing:-.055em;margin:0}.pl-top p{color:#6d7892;margin:5px 0 0}.pl-link{color:#5a4eac;text-decoration:none;font-weight:800;font-size:13px}.pl-button{background:#5c50ae;color:white!important;border-radius:10px;padding:14px 19px;text-decoration:none;font-weight:800;font-size:13px;white-space:nowrap}.pl-button:hover{background:#443a91}.pl-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-bottom:22px}.pl-stat{background:white;border:1px solid #e0e4f1;border-radius:15px;padding:21px}.pl-stat small{display:block;color:#75809c;font-weight:700;margin-bottom:7px}.pl-stat strong{font:700 26px Outfit}.pl-table-wrap{overflow:auto;background:white;border:1px solid #e0e4f1;border-radius:17px}.pl-table{border-collapse:collapse;width:100%;min-width:730px}.pl-table th{text-align:left;color:#64708d;font-size:12px;padding:17px 20px;background:#f9faff}.pl-table td{border-top:1px solid #e9ecf5;padding:18px 20px;font-size:13px}.pl-table tr:hover td{background:#fafaff}.pl-status{border-radius:8px;background:#fff0cb;color:#81611e;padding:7px 10px;font-weight:800;font-size:11px}.pl-status.completed{background:#e0f4e9;color:#176a49}.pl-status.processing{background:#e8e7fa;color:#594d9c}.pl-status.failed{background:#ffe4e0;color:#923e37}.pl-empty{background:white;border:1px solid #e0e4f1;border-radius:20px;padding:clamp(34px,6vw,80px);text-align:center}.pl-empty-mark{width:88px;height:88px;margin:auto auto 23px;border:1px solid #cac5ee;border-radius:24px;display:grid;place-items:center;color:#655ab5;font:700 40px Outfit;background:#f0eefc}.pl-empty h2{font:700 clamp(25px,3vw,36px) Outfit;letter-spacing:-.04em;margin:0 0 7px}.pl-empty p{color:#707b96;margin:0 auto 26px;max-width:500px;line-height:1.6}.pl-alert{padding:13px 17px;background:#e3f3ea;color:#176a49;border-radius:10px;margin:12px 0 22px}
@media(max-width:650px){.pl-top{display:block}.pl-top .pl-button{display:inline-block;margin-top:20px}.pl-summary{grid-template-columns:1fr}}
</style>
<main class="pl"><div class="pl-inner"><a class="pl-link" href="{{ route('dashboard') }}">Back to dashboard</a><header class="pl-top"><div><h1>Payments.</h1><p>{{ auth()->user()?->isAdmin() ? 'Track and verify transfers across Tasmiya.' : 'Keep every payment request and receipt in one place.' }}</p></div><a class="pl-button" href="{{ route('payments.create') }}">Create payment</a></header>
@if(session('success'))<div class="pl-alert">{{ session('success') }}</div>@endif
@if($payments->isEmpty())<section class="pl-empty"><div class="pl-empty-mark" aria-hidden="true">T</div><h2>No payments yet.</h2><p>Once a payment is created, its transfer instructions, submitted reference and verification status will appear here.</p><a class="pl-button" href="{{ route('payments.create') }}">Create the first payment</a></section>
@else
<div class="pl-summary"><div class="pl-stat"><small>Payments on this page</small><strong>{{ $payments->count() }}</strong></div><div class="pl-stat"><small>Awaiting action</small><strong>{{ $payments->whereIn('status',['pending','processing'])->count() }}</strong></div><div class="pl-stat"><small>Verified</small><strong>{{ $payments->where('status','completed')->count() }}</strong></div></div>
<div class="pl-table-wrap"><table class="pl-table"><thead><tr><th>Payment</th><th>Service</th><th>Amount</th><th>Method</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>@foreach($payments as $payment)<tr><td><strong>#{{ $payment->id }}</strong></td><td>{{ $payment->service?->name ?? 'Custom' }}</td><td>PKR {{ number_format($payment->amount,2) }}</td><td>{{ ucwords(str_replace('_',' ',$payment->payment_method)) }}</td><td><span class="pl-status {{ $payment->status }}">{{ ucfirst($payment->status) }}</span></td><td>{{ $payment->created_at->format('j M Y') }}</td><td><a class="pl-link" href="{{ route('payments.show',$payment) }}">View</a></td></tr>@endforeach</tbody></table></div>
@if($payments->hasPages())<div style="margin-top:20px">{{ $payments->links() }}</div>@endif
@endif</div></main>
@endsection
