<?php

return [
    'icons' => [
        'tax' => 'Tax document',
        'audit' => 'Checklist',
        'code' => 'Web and app',
        'cloud' => 'Cloud',
        'support' => 'Support desk',
        'security' => 'Security',
        'data' => 'Database',
        'growth' => 'Growth',
        'commerce' => 'Online store',
        'design' => 'Design',
    ],
    'divisions' => [
        'fbr-taxation' => [
            'icon' => 'tax',
            'focus' => ['Tax returns and filing', 'Compliance and audits', 'Registration and planning'],
        ],
        'it-digital' => [
            'icon' => 'code',
            'focus' => ['Websites and apps', 'Cloud and data', 'Digital growth'],
        ],
        'tech-support' => [
            'icon' => 'support',
            'focus' => ['Networks and devices', 'Maintenance', 'Remote troubleshooting'],
        ],
    ],
    'services' => [
        'tax-consultation' => ['icon' => 'tax', 'focus' => ['Tax position review', 'Practical guidance']],
        'compliance-audit' => ['icon' => 'audit', 'focus' => ['Record review', 'Compliance gaps']],
        'tax-planning-strategy' => ['icon' => 'growth', 'focus' => ['Planning', 'Tax efficiency']],
        'corporate-tax' => ['icon' => 'tax', 'focus' => ['Corporate returns', 'Compliance']],
        'freelancer-tax' => ['icon' => 'tax', 'focus' => ['Independent income', 'Filing']],
        'withholding-tax' => ['icon' => 'audit', 'focus' => ['Deductions', 'Reporting']],
        'sales-tax-return-filing' => ['icon' => 'tax', 'focus' => ['Return preparation', 'Submission']],
        'income-tax-return' => ['icon' => 'tax', 'focus' => ['Annual return', 'Documentation']],
        'tax-registration-services' => ['icon' => 'audit', 'focus' => ['Registration', 'FBR setup']],
        'vat-excise-duty' => ['icon' => 'tax', 'focus' => ['Duty review', 'Compliance']],
        'web-development' => ['icon' => 'code', 'focus' => ['Website build', 'Launch support']],
        'mobile-app-development' => ['icon' => 'code', 'focus' => ['App design', 'Development']],
        'cloud-solutions' => ['icon' => 'cloud', 'focus' => ['Cloud setup', 'Scalability']],
        'system-administration' => ['icon' => 'support', 'focus' => ['Monitoring', 'Maintenance']],
        'cloud-migration' => ['icon' => 'cloud', 'focus' => ['Migration plan', 'Data move']],
        'it-consulting' => ['icon' => 'growth', 'focus' => ['Assessment', 'Technology roadmap']],
        'digital-marketing' => ['icon' => 'growth', 'focus' => ['Campaigns', 'Performance']],
        'ecommerce-solutions' => ['icon' => 'commerce', 'focus' => ['Storefront', 'Checkout']],
        'database-management' => ['icon' => 'data', 'focus' => ['Database design', 'Performance']],
        'ui-ux-design' => ['icon' => 'design', 'focus' => ['User flows', 'Interface design']],
        'hardware-support' => ['icon' => 'support', 'focus' => ['Diagnosis', 'Repair']],
        'software-support' => ['icon' => 'support', 'focus' => ['Troubleshooting', 'Configuration']],
        'network-support' => ['icon' => 'cloud', 'focus' => ['Connectivity', 'Wi-Fi and LAN']],
        'system-maintenance' => ['icon' => 'support', 'focus' => ['Updates', 'Preventive checks']],
        'data-recovery' => ['icon' => 'data', 'focus' => ['Recovery assessment', 'Restoration']],
        'security-solutions' => ['icon' => 'security', 'focus' => ['Risk review', 'Protection']],
        'remote-it-support' => ['icon' => 'support', 'focus' => ['Remote diagnosis', 'Issue resolution']],
        'printer-peripheral-support' => ['icon' => 'support', 'focus' => ['Device setup', 'Troubleshooting']],
    ],
];
